"use client";
import {useEffect,useState,type ReactNode} from 'react';
import {cleanPanels,type PanelPreference} from '@/lib/market-research';
export default function PanelLayout({scope,items}:{scope:string;items:{id:string;title:string;content:ReactNode}[]}){
 const ids=items.map(i=>i.id),[pref,setPref]=useState<PanelPreference>({order:ids,hidden:[]}),[ready,setReady]=useState(false),[editing,setEditing]=useState(false),[warning,setWarning]=useState('');
 useEffect(()=>{try{setPref(cleanPanels(JSON.parse(localStorage.getItem('baltatool.layout.'+scope)??'{}'),ids));}catch{setPref(cleanPanels({},ids));}setReady(true);},[scope]); // ids are a fixed set for this workspace
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('baltatool.layout.'+scope,JSON.stringify(pref));setWarning('');}catch{setWarning('브라우저 설정을 저장할 수 없습니다. 현재 화면에만 적용됩니다.');}},[pref,ready,scope]);
 useEffect(()=>{const reveal=(event:Event)=>{const id=(event as CustomEvent<string>).detail;if(!ids.includes(id))return;setPref(p=>({...p,hidden:p.hidden.filter(x=>x!==id)}));setTimeout(()=>document.getElementById(id==='main-chart'?'market-charts':'records')?.scrollIntoView({behavior:'smooth',block:'start'}),50);};window.addEventListener('balta-reveal-panel',reveal);return()=>window.removeEventListener('balta-reveal-panel',reveal);},[]);
 function move(id:string,delta:number){setPref(old=>{const order=[...old.order],i=order.indexOf(id),j=i+delta;if(j<0||j>=order.length)return old;[order[i],order[j]]=[order[j],order[i]];return {...old,order};});}
 return <><div className="panel layout-controls"><div className="toolbar"><button className="button small" onClick={()=>setEditing(v=>!v)} aria-expanded={editing}>대시보드 배치 {editing?'닫기':'설정'}</button><span className="panel-subtitle">이 브라우저에 저장 · 위/아래 이동 및 숨기기</span></div>{warning&&<p role="status">{warning}</p>}{editing&&<div className="layout-list">{pref.order.map((id,index)=>{const item=items.find(x=>x.id===id);if(!item)return null;return <div className="layout-row" key={id}><label><input type="checkbox" checked={!pref.hidden.includes(id)} onChange={e=>setPref(p=>({...p,hidden:e.target.checked?p.hidden.filter(x=>x!==id):[...p.hidden,id]}))}/>{item.title}</label><span><button className="button small" aria-label={item.title+' 위로'} disabled={index===0} onClick={()=>move(id,-1)}>↑</button><button className="button small" aria-label={item.title+' 아래로'} disabled={index===pref.order.length-1} onClick={()=>move(id,1)}>↓</button></span></div>;})}<button className="button small" onClick={()=>setPref({order:ids,hidden:[]})}>기본 배치 복원</button></div>}</div>{pref.order.filter(id=>!pref.hidden.includes(id)).map(id=><div key={id}>{items.find(x=>x.id===id)?.content}</div>)}</>;
}
