"use client";
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {useEffect,useMemo,useState} from 'react';
import {useMarketFeed} from './useMarketFeed';
import {kstParts,isValidDate,minuteLabel,formatNumber as f} from '@/lib/balta-model';
import {buildMarketEvents} from '@/lib/balta-signals';
import {type ChartKind,type Domain} from './chart-model';
const Chart=dynamic(()=>import('./MarketCharts'),{ssr:false});
function Notes({date}:{date:string}){
 const [body,setBody]=useState(''),[tags,setTags]=useState(''),[version,setVersion]=useState(0),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();setReady(false);fetch('/api/market/notes?date='+date,{signal:c.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);if(!c.signal.aborted){setBody(j.note?.body??'');setTags(j.note?.tags??'');setVersion(j.note?.version??0);setReady(true);setDirty(false);setMessage('');}}).catch(e=>{if(!c.signal.aborted)setMessage(e.message);});return()=>c.abort();},[date,retry]);
 useEffect(()=>{const h=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h);},[dirty]);
 async function save(){setBusy(true);try{const r=await fetch('/api/market/notes?date='+date,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({body,tags,version})});const j=await r.json();if(!r.ok)throw Error(j.error);setVersion(j.note.version);setDirty(false);setMessage('저장 완료');}catch(e){setMessage(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}
 return <section className="panel diagnostic-body"><h2 className="panel-title">{date} 복기 메모</h2><small>현재 대시보드는 공용 로그인 방식입니다. 메모도 같은 대시보드 사용자들과 공유됩니다.</small><textarea aria-label="복기 메모" rows={8} maxLength={10000} value={body} disabled={!ready||busy} onChange={e=>{setBody(e.target.value);setDirty(true);}} style={{background:'#11151a',color:'#e0e5ee',padding:14,border:'1px solid #343b46',borderRadius:8}}/><input aria-label="메모 태그" placeholder="태그: 수급반전, 오후강세" maxLength={200} value={tags} disabled={!ready||busy} onChange={e=>{setTags(e.target.value);setDirty(true);}}/><div className="toolbar"><button className="button" disabled={!ready||busy||!dirty} onClick={()=>void save()}>{busy?'저장 중':'메모 저장'}</button><button className="button" disabled={busy} onClick={()=>{if(!dirty||confirm('저장하지 않은 내용을 버리고 다시 불러올까요?'))setRetry(v=>v+1);}}>다시 불러오기</button><span role="status">{dirty?'미저장 · ':''}{message}</span></div><small>날짜 이동 전 메모를 저장하세요. 저장 실패 시 입력 내용은 이 화면에 유지됩니다.</small></section>;
}
export default function ReplayWorkspace(){
 const [date,setDate]=useState(''),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(5),[minute,setMinute]=useState(540),[kind,setKind]=useState<ChartKind>('flow'),[domain,setDomain]=useState<Domain>([540,930]);
 useEffect(()=>{const requested=new URLSearchParams(location.search).get('date');setDate(requested&&isValidDate(requested)?requested:kstParts().date);},[]);
 const feed=useMarketFeed(date,false,false),last=feed.rows.at(-1)?.minute??540;
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setMinute(m=>{if(m>=last){setPlaying(false);return m;}return Math.min(last,m+1);}),1000/speed);return()=>clearInterval(timer);},[playing,speed,last]);
 const visible=useMemo(()=>feed.rows.filter(r=>r.minute<=minute),[feed.rows,minute]),events=useMemo(()=>buildMarketEvents(visible),[visible]),current=visible.at(-1);
 return <main style={{maxWidth:1400,margin:'auto',padding:'32px 20px'}}><div className="page-heading"><div><h1>시장 복기</h1><p>저장된 하루를 다시 읽고 기록하세요.</p></div><div className="toolbar"><a className="button" href="/">대시보드</a><a className="button" href="/history">캘린더</a><a className="button" href="/research">메모 검색 · 리서치</a><input aria-label="복기 날짜" type="date" value={date} onChange={e=>{if(isValidDate(e.target.value))location.assign('/replay?date='+e.target.value);}}/></div></div>
 <section className="panel diagnostic-body"><div className="toolbar"><button className="button" disabled={!feed.rows.length} onClick={()=>{if(minute>=last)setMinute(540);setPlaying(v=>!v);}}>{playing?'일시정지':'재생'}</button><button className="button" onClick={()=>{setPlaying(false);setMinute(540);}}>처음으로</button><select aria-label="재생 속도" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,5,20].map(s=><option key={s} value={s}>{s}배속</option>)}</select><strong>{minuteLabel(minute)}</strong><select aria-label="차트 지표" value={kind} onChange={e=>setKind(e.target.value as ChartKind)}><option value="flow">투자자 수급</option><option value="breadth">시장폭</option><option value="kospi">KOSPI</option><option value="kosdaq">KOSDAQ</option></select></div><small>1배속은 1초당 시장 시간 1분입니다. 누락 분은 건너 채우지 않으며, 선택 시각 이후 기록과 신호는 숨깁니다.</small><input aria-label="재생 시각" type="range" min={540} max={Math.max(541,last)} value={minute} onChange={e=>{setPlaying(false);setMinute(Number(e.target.value));}}/>
 {feed.loading?<p>기록 조회 중…</p>:feed.error?<p role="alert">{feed.error}<button className="button" onClick={()=>void feed.refresh(true)}>다시 조회</button></p>:!feed.rows.length?<p>해당 날짜에 저장 기록이 없습니다.</p>:<><p>마지막 관측 {current?.time??'없음'} {current&&current.minute!==minute?'· 선택 분 기록 누락':''} · KOSPI {f(current?.kospi,2)} · 시장폭 {f(current?.diff,0,true)}</p><Chart rows={visible} events={events} kind={kind} domain={domain} onDomainChange={setDomain} showMarkers onReset={()=>setDomain([540,930])}/><details open><summary>현재까지 신호 {events.length}건</summary>{events.slice(0,10).map(e=><p key={e.id}>{e.time} · {e.label}</p>)}</details></>}
 </section>{date&&<Notes key={date} date={date}/>}<p><Link href={'/daily?date='+date}>해당 날짜 전체 분석</Link></p></main>;
}
