"use client";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,Brush,ReferenceLine,ReferenceDot} from 'recharts';
import {type MarketRow,minuteLabel} from '@/lib/balta-model';
import {overlayRows,overlayDaySummaries,type OverlayMetric,type OverlaySession} from '@/lib/market-research';
const colors=['#5294ff','#ff667a','#f2ce53','#a58aff'];
export default function ResearchCharts({days,metric,relative,session='extended',showTurns=true}:{days:{date:string;rows:MarketRow[]}[];metric:OverlayMetric;relative:boolean;session?:OverlaySession;showTurns?:boolean}){
 const data=overlayRows(days,metric,relative,session),summaries=overlayDaySummaries(days,metric,relative,session),unit=metric==='diff'?'종목':metric==='kospi'||metric==='kosdaq'?relative?'%':'pt':'억원';
 return <div style={{height:460,width:'100%'}}><ResponsiveContainer><LineChart data={data} margin={{top:18,right:22,bottom:10,left:12}}><CartesianGrid stroke="#252d38" strokeDasharray="3 3"/><XAxis dataKey="minute" type="number" domain={session==='regular'?[540,930]:[540,1200]} ticks={session==='regular'?[540,600,660,720,780,840,900,930]:[540,600,660,720,780,840,900,930,960,1020,1080,1140,1200]} tickFormatter={minuteLabel} minTickGap={34} stroke="#8d98a8"/><YAxis width={74} domain={['auto','auto']} stroke="#8d98a8" tickFormatter={v=>Number(v).toLocaleString('ko-KR',{maximumFractionDigits:1})}/><Tooltip labelFormatter={v=>minuteLabel(Number(v))} formatter={(v)=>[Number(v).toLocaleString('ko-KR',{maximumFractionDigits:2})+' '+unit]} contentStyle={{background:'#14191f',border:'1px solid #343b46',color:'#e0e5ee'}}/><Legend/>{session==='extended'&&<><ReferenceLine x={930} stroke="#6f7783" strokeDasharray="4 4" label={{value:'15:30',position:'insideTopRight',fill:'#8993a1',fontSize:11}}/><ReferenceLine x={960} stroke="#4f6684" strokeDasharray="4 4" label={{value:'애프터 16:00',position:'insideTopRight',fill:'#8da2bf',fontSize:11}}/></>}{days.map((d,i)=><Line key={d.date} dataKey={d.date} name={d.date} stroke={colors[i]} strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/>)}{showTurns&&summaries.flatMap((s,i)=>s.turningPoints.map((t,n)=><ReferenceDot key={s.date+'-'+n} x={t.minute} y={t.value} r={4} fill={colors[i]} stroke="#0b0e12" strokeWidth={2} ifOverflow="extendDomain"/>))}<Brush dataKey="minute" tickFormatter={minuteLabel} height={25} stroke="#5294ff" fill="#14191f"/></LineChart></ResponsiveContainer></div>;
}
