"use client";
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useMarketFeed} from './useMarketFeed';
import {kstParts,isValidDate,moveDate,minuteLabel,formatNumber as f,type MarketRow} from '@/lib/balta-model';
import {sessionComparison,rangeChunks,type Sector} from '@/lib/market-research';
import {detectChanges} from '@/lib/market-diagnostics';
const Charts=dynamic(()=>import('./ResearchCharts'),{ssr:false,loading:()=> <p>차트 준비 중…</p>});
async function getJson(url:string,signal:AbortSignal){const r=await fetch(url,{signal:AbortSignal.any([signal,AbortSignal.timeout(55000)]),cache:'no-store'});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||'조회하지 못했습니다.');return j;}
const errorText=(e:unknown)=>e instanceof Error?e.message:'조회 실패';
function SectorMap({date}:{date:string}){
 const [data,setData]=useState<{time:string;items:Sector[]}|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[market,setMarket]=useState('all'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Sector|null>(null);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setData(null);setSelected(null);getJson('/api/market/sectors?date='+date,c.signal).then(j=>{if(!c.signal.aborted)setData({time:j.snapshot?.time??'',items:j.snapshot?.market_data?.sectors??[]});}).catch(e=>{if(!c.signal.aborted)setError(errorText(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[date,refresh]);
 useEffect(()=>{if(date!==kstParts().date)return;const timer=setInterval(()=>{if(!document.hidden)setRefresh(n=>n+1);},60000);return()=>clearInterval(timer);},[date]);
 const items=(data?.items??[]).filter(s=>(market==='all'||s.market===market)&&s.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(b.change??-Infinity)-(a.change??-Infinity));
 return <section className="panel diagnostic-body"><div className="toolbar"><h2 className="panel-title">섹터 강도 지도</h2><select aria-label="업종 시장" value={market} onChange={e=>setMarket(e.target.value)}><option value="all">양 시장</option><option value="kospi">KOSPI</option><option value="kosdaq">KOSDAQ</option></select><input aria-label="업종 검색" placeholder="업종명 검색" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button small" onClick={()=>setRefresh(n=>n+1)}>새로고침</button></div><p>{data?.time||'—'} 저장 기준 · 전일 대비 등락률 순 · 같은 크기의 셀 · 빨강 상승 / 파랑 하락</p>{loading?<p>업종 기록 조회 중…</p>:error?<p role="alert">{error}</p>:!items.length?<div className="empty-state">표시할 업종 기록이 없습니다. 업데이트 이후 수집된 날짜를 선택하거나 검색 조건을 확인하세요.</div>:<div className="sector-map">{items.map(s=><button key={s.market+s.code} className="sector-tile" style={{background:s.change===null||s.change===0?'#202630':s.change>0?`rgba(214,57,78,${Math.min(.8,.18+Math.abs(s.change)*.12)})`:`rgba(46,103,208,${Math.min(.8,.18+Math.abs(s.change)*.12)})`}} onClick={()=>setSelected(s)}><small>{s.market==='kospi'?'KOSPI':'KOSDAQ'}</small><strong>{s.name}</strong><b>{f(s.change,2,true)}%</b></button>)}</div>}{selected&&<div className="research-detail"><strong>{selected.name}</strong><p>업종 코드 {selected.code} · 지수 {f(selected.price,2)} · 전일 대비 {f(selected.change,2,true)}%</p></div>}<small>KIS 업종 분류를 그대로 사용합니다. 반도체·자동차 같은 개별 테마 분류와 다를 수 있으며 종합·규모별 분류가 함께 포함될 수 있습니다. 셀 면적은 시가총액이나 지수 기여도를 의미하지 않습니다. 과거 업종 데이터는 소급 생성하지 않습니다.</small></section>;
}
function DayComparison({date}:{date:string}){
 const [dates,setDates]=useState([date,moveDate(date,-1)]),[metric,setMetric]=useState<'foreignFlow'|'instFlow'|'indivFlow'|'diff'|'kospi'|'kosdaq'>('foreignFlow'),[relative,setRelative]=useState(true),[days,setDays]=useState<{date:string;rows:MarketRow[]}[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');const pending=useRef<AbortController|null>(null);
 useEffect(()=>()=>pending.current?.abort(),[]);
 async function load(){pending.current?.abort();const c=new AbortController();pending.current=c;setError('');setDays([]);const unique=[...new Set(dates)];if(unique.some(d=>!isValidDate(d)||d>kstParts().date)){setError('오늘 이전의 유효한 날짜를 선택하세요.');return;}setLoading(true);
 try{const result=await Promise.all(unique.map(async d=>{const j=await getJson('/api/market/daily?date='+d,c.signal);return {date:d,rows:j.rows as MarketRow[]};}));if(!c.signal.aborted)setDays(result);}catch(e){if(!c.signal.aborted)setError(errorText(e));}finally{if(!c.signal.aborted)setLoading(false);}}
 return <section className="panel diagnostic-body"><h2 className="panel-title">여러 날짜 차트 비교</h2><div className="toolbar">{dates.map((d,i)=><label key={i}>날짜 {i+1} <input aria-label={'비교 날짜 '+(i+1)} type="date" value={d} max={kstParts().date} onChange={e=>setDates(v=>v.map((a,n)=>n===i?e.target.value:a))}/></label>)}<button className="button small" disabled={dates.length>=4} onClick={()=>setDates(v=>[...v,moveDate(date,-v.length)])}>날짜 추가</button><button className="button small" disabled={dates.length<=2} onClick={()=>setDates(v=>v.slice(0,-1))}>마지막 제거</button><button className="button" onClick={()=>void load()} disabled={loading}>비교 조회</button></div><div className="toolbar"><select aria-label="비교 지표" value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}>{[['foreignFlow','외국인 수급'],['instFlow','기관 수급'],['indivFlow','개인 수급'],['diff','시장폭'],['kospi','KOSPI'],['kosdaq','KOSDAQ']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{['kospi','kosdaq'].includes(metric)&&<label><input type="checkbox" checked={relative} onChange={e=>setRelative(e.target.checked)}/>첫 관측 대비 등락률</label>}</div>{loading?<p>날짜별 기록 조회 중…</p>:error?<p role="alert">{error}</p>:days.length?<><Charts days={days} metric={metric} relative={relative}/><p>{days.map(d=>d.date+' · '+d.rows.length+'개 기록').join(' / ')}</p></>:<p>2~4개 날짜를 선택하고 비교 조회를 누르세요.</p>}<small>가로축은 동일한 KST 시각입니다. 없는 분과 비정상 수급·시장폭은 선을 끊습니다. 지수 등락률은 각 날짜 첫 유효 관측 대비이며 전일 대비가 아닙니다. 색상은 투자자가 아닌 날짜를 구분합니다. 날짜 변경 후 비교 조회를 다시 눌러 적용하세요.</small></section>;
}
function SessionAnalysis({date}:{date:string}){
 const feed=useMarketFeed(date,false,false),sessions=useMemo(()=>sessionComparison(feed.rows),[feed.rows]),crossings=useMemo(()=>detectChanges(feed.rows),[feed.rows]);
 const a=sessions[0].kospi,b=sessions[1].kospi;
 const summary=a===null||b===null?'09:00·12:00·15:30 기록이 모두 있어야 오전·오후 방향을 비교할 수 있습니다.':a>0&&b<0?'KOSPI 오전 상승 → 오후 하락':a<0&&b>0?'KOSPI 오전 하락 → 오후 상승':a>0&&b>0?'KOSPI 오전·오후 모두 상승':a<0&&b<0?'KOSPI 오전·오후 모두 하락':'KOSPI 방향 변화가 뚜렷하지 않습니다.';
 return <section className="panel diagnostic-body"><h2 className="panel-title">장 초반·후반 분석</h2>{feed.loading?<p>기록 조회 중…</p>:feed.error?<p role="alert">{feed.error}<button className="button small" onClick={()=>void feed.refresh(true)}>다시 조회</button></p>:<><strong>{summary}</strong><div className="diagnostic-table"><table><thead><tr><th>구간</th><th>KOSPI</th><th>KOSDAQ</th><th>시장폭 변화</th><th>외국인</th><th>기관</th><th>개인</th><th>관측 / 기대</th></tr></thead><tbody>{sessions.map(s=><tr key={s.label}><td>{s.label}<small>{minuteLabel(s.start)}–{minuteLabel(s.end)}</small></td><td>{f(s.kospi,2,true)}%</td><td>{f(s.kosdaq,2,true)}%</td><td>{f(s.breadth,0,true)}</td><td>{f(s.foreign,0,true)}</td><td>{f(s.inst,0,true)}</td><td>{f(s.indiv,0,true)}</td><td>{s.count} / {s.expected}</td></tr>)}</tbody></table></div><h3>수급 0선 전환 시각</h3>{crossings.length?crossings.map((c,i)=><Link className="research-note" key={i} href={'/replay?date='+date}><strong>{c.time} · {c.label}</strong><small>{c.detail}</small></Link>):<p>연속된 정상 기록에서 감지된 전환이 없습니다.</p>}</>}<small>오전은 09:00~12:00, 오후는 12:00~15:30입니다. 수급은 구간 끝 누적값 − 시작 누적값(억원)이며 정확한 경계 기록이 없으면 계산하지 않습니다. 오전 수급은 09:00 이전 누적분을 포함하지 않습니다. 표의 지수는 구간 변화율입니다.</small></section>;
}
function NoteSearch(){
 const [text,setText]=useState(''),[tag,setTag]=useState(''),[query,setQuery]=useState({q:'',tag:'',page:0,nonce:0}),[rows,setRows]=useState<{trade_date:string;body:string;tags:string}[]>([]),[more,setMore]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setRows([]);getJson('/api/market/notes/search?'+new URLSearchParams({q:query.q,tag:query.tag,page:String(query.page)}),c.signal).then(j=>{if(!c.signal.aborted){setRows(j.rows);setMore(j.hasMore);}}).catch(e=>{if(!c.signal.aborted)setError(errorText(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[query]);
 return <section className="panel diagnostic-body"><h2 className="panel-title">메모 검색 · 태그 필터</h2><form className="toolbar" onSubmit={e=>{e.preventDefault();setQuery({q:text,tag,page:0,nonce:Date.now()});}}><input aria-label="메모 내용 검색" maxLength={100} value={text} onChange={e=>setText(e.target.value)} placeholder="내용 또는 날짜 검색"/><input aria-label="태그 필터" maxLength={100} value={tag} onChange={e=>setTag(e.target.value)} placeholder="태그 정확히 일치"/><button className="button" type="submit">검색</button></form><small>쉼표로 구분해 저장한 태그 중 하나와 일치하는 메모를 찾습니다. 현재 대시보드의 공유 메모입니다.</small>{loading?<p>메모 검색 중…</p>:error?<p role="alert">{error}<button className="button small" onClick={()=>setQuery(v=>({...v,nonce:Date.now()}))}>다시 시도</button></p>:rows.length?rows.map(n=><Link className="research-note" key={n.trade_date} href={'/replay?date='+n.trade_date}><strong>{n.trade_date}</strong><p>{n.body.slice(0,300)||'내용 없는 메모'}</p><small>{n.tags||'태그 없음'} · 복기에서 열기</small></Link>):<p>검색 결과가 없습니다.</p>}<div className="toolbar"><button className="button small" disabled={loading||query.page===0} onClick={()=>setQuery(v=>({...v,page:v.page-1}))}>이전</button><span>{query.page+1} 페이지</span><button className="button small" disabled={loading||!!error||!more} onClick={()=>setQuery(v=>({...v,page:v.page+1}))}>다음</button></div></section>;
}
type Stat={label:string;count:number;pending:number;wins:number;sum:number};
function PeriodPerformance({date}:{date:string}){
 const [months,setMonths]=useState(1),[market,setMarket]=useState('kospi'),[horizon,setHorizon]=useState('30'),[stats,setStats]=useState<Stat[]>([]),[dates,setDates]=useState<string[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[resultLabel,setResultLabel]=useState('');const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 async function run(){controller.current?.abort();const c=new AbortController();controller.current=c;const range=rangeChunks(date,months);setBusy(true);setStats([]);setDates([]);setError('');setResultLabel('');setProgress('조회 시작');const combined=new Map<string,Stat>(),seen=new Set<string>();
 try{for(let i=0;i<range.chunks.length;i++){const part=range.chunks[i];const j=await getJson('/api/market/research?'+new URLSearchParams({...part,market,horizon}),c.signal);if(c.signal.aborted)return;for(const g of j.stats as Stat[]){const old=combined.get(g.label);combined.set(g.label,old?{...g,count:g.count+old.count,pending:g.pending+old.pending,wins:g.wins+old.wins,sum:g.sum+old.sum}:g);}for(const d of j.dates)seen.add(d);setProgress(`${i+1} / ${range.chunks.length}개 구간 조회`);}
 if(!c.signal.aborted){setStats([...combined.values()].sort((a,b)=>b.count-a.count));setDates([...seen].sort());setResultLabel(range.start+' ~ '+date+' · '+market.toUpperCase()+' · '+(horizon==='close'?'15:30':horizon+'분 후'));setProgress('전체 조회 완료');}
 }catch(e){if(!c.signal.aborted){setError(errorText(e)+' 부분 결과는 표시하지 않습니다.');setProgress('조회 중단');}}finally{if(controller.current===c)setBusy(false);}}
 return <section className="panel diagnostic-body"><h2 className="panel-title">여러 날 신호 성과</h2><div className="toolbar"><select aria-label="분석 기간" disabled={busy} value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={1}>최근 1개월</option><option value={3}>최근 3개월</option></select><select aria-label="분석 지수" disabled={busy} value={market} onChange={e=>setMarket(e.target.value)}><option value="kospi">KOSPI</option><option value="kosdaq">KOSDAQ</option></select><select aria-label="평가 시각" disabled={busy} value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="30">30분 후</option><option value="60">1시간 후</option><option value="close">15:30 기록</option></select><button className="button" disabled={busy} onClick={()=>void run()}>기간 분석</button>{busy&&<button className="button small" onClick={()=>{controller.current?.abort();setBusy(false);setProgress('취소됨');}}>취소</button>}</div><p role="status">{progress||'기간 분석을 누르면 저장된 기록을 주 단위로 나눠 조회합니다.'}</p>{error&&<p role="alert">{error}</p>}{resultLabel&&<><strong>{resultLabel}</strong><p>기록이 있는 {dates.length}일 · 휴장일 제외</p><div className="diagnostic-table"><table><thead><tr><th>신호</th><th>평가 표본</th><th>미평가</th><th>평균 지수 등락</th><th>방향 일치율</th></tr></thead><tbody>{stats.map(s=><tr key={s.label}><td>{s.label}</td><td>{s.count}</td><td>{s.pending}</td><td>{f(s.count?s.sum/s.count:null,2,true)}%</td><td>{f(s.count?s.wins/s.count*100:null,1)}%</td></tr>)}</tbody></table></div>{!stats.length&&<p>해당 기간에 평가 가능한 방향성 수집 신호가 없습니다.</p>}<details><summary>관측 날짜 확인</summary><p>{dates.join(', ')||'없음'}</p></details></>}<small>저장된 방향성 신호만 사용하며, 정확한 평가 시각의 가격이 없으면 미평가입니다. 같은 날짜·분·유형의 중복은 제외합니다. 하락 신호 후 하락하면 방향 일치입니다. 반복 표본은 구간이 겹칠 수 있고 매매 비용을 반영하지 않아 전략 수익률이 아닙니다. 데이터가 없는 거래일은 성과에 포함되지 않습니다. 오류 출처로 표시된 지수는 제외하며, 출처 정보가 없던 과거 가격은 별도 검증할 수 없습니다.</small></section>;
}
const tabs=[['sectors','섹터 지도'],['compare','날짜 비교'],['session','오전 · 오후'],['notes','메모 검색'],['performance','기간 성과']] as const;
export default function ResearchWorkspace(){
 const [date,setDate]=useState(''),[tab,setTab]=useState<string>('sectors');
 useEffect(()=>{const d=new URLSearchParams(location.search).get('date'),today=kstParts().date;setDate(d&&isValidDate(d)&&d<=today?d:today);},[]);
 return <main className="research-workspace"><header className="page-heading"><div><h1>시장 리서치</h1><p>업종 흐름, 날짜 비교, 기록과 신호를 함께 분석합니다.</p></div><div className="toolbar"><Link className="button" href="/">대시보드</Link><Link className="button" href="/history">캘린더</Link><label>기준일 <input aria-label="리서치 기준 날짜" type="date" value={date} max={kstParts().date} onChange={e=>{if(isValidDate(e.target.value)&&e.target.value<=kstParts().date)setDate(e.target.value);}}/></label></div></header><nav className="research-tabs" aria-label="리서치 기능">{tabs.map(([key,label])=><button className={'button '+(key===tab?'primary':'')} aria-pressed={key===tab} key={key} onClick={()=>setTab(key)}>{label}</button>)}</nav>{date&&<div key={date+tab}>{tab==='sectors'?<SectorMap date={date}/>:tab==='compare'?<DayComparison date={date}/>:tab==='session'?<SessionAnalysis date={date}/>:tab==='notes'?<NoteSearch/>:<PeriodPerformance date={date}/>}</div>}</main>;
}
