"use client";
import { Fragment, useEffect, useMemo, useState } from 'react';
import { reversalCSV, reversalLabels, reversalStatus, type ReversalResult } from '@/lib/reversal-model';
import useReversalScanner from './useReversalScanner';
import s from './ReversalScanner.module.css';
const number=(n:number|null|undefined,d=0)=>n==null?'—':n.toLocaleString('ko-KR',{maximumFractionDigits:d,minimumFractionDigits:d});
const percent=(n:number|null|undefined)=>n==null?'—':`${n>0?'+':''}${number(n,2)}%`;
const time=(iso:string)=>iso?new Date(iso).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'—';
const checkNames={pass:'통과',fail:'제외',unknown:'미확인'};
const favoriteKey='baltatool:reversal-favorites:v1';
function Spark({values}:{values:number[]}) {
  if(values.length<2)return <span>—</span>;
  const lo=Math.min(...values),hi=Math.max(...values),points=values.map((v,i)=>`${2+i/(values.length-1)*80},${27-(v-lo)/Math.max(hi-lo,1)*24}`).join(' ');
  return <svg width="84" height="32" viewBox="0 0 84 32" role="img" aria-label="최근 조회 일봉 가격 흐름"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.6"/></svg>;
}
export default function ReversalScanner() {
  const {scan,running,error,storageError,start,stop}=useReversalScanner();
  const [filter,setFilter]=useState('match'),[market,setMarket]=useState('all'),[search,setSearch]=useState(''),[sort,setSort]=useState('decline'),[selected,setSelected]=useState('');
  const [favorites,setFavorites]=useState<string[]>([]),[onlyFavorites,setOnlyFavorites]=useState(false),[favoriteError,setFavoriteError]=useState('');
  useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(favoriteKey)||'[]');if(Array.isArray(v))setFavorites(v.filter(c=>typeof c==='string'&&/^\d{6}$/.test(c)).slice(0,5000));}catch{}},[]);
  function toggle(code:string){const next=favorites.includes(code)?favorites.filter(c=>c!==code):[...favorites,code];setFavorites(next);try{localStorage.setItem(favoriteKey,JSON.stringify(next));setFavoriteError('');}catch{setFavoriteError('관심 표시를 브라우저에 저장하지 못했습니다.');}}
  const counts=useMemo(()=>({match:scan.rows.filter(r=>r.status==='match').length,review:scan.rows.filter(r=>r.status==='review').length,excluded:scan.rows.filter(r=>r.status==='excluded').length}),[scan.rows]);
  const rows=useMemo(()=>scan.rows.filter(r=>(filter==='all'||r.status===filter)&&(market==='all'||r.market===market)&&(!onlyFavorites||favorites.includes(r.code))&&(r.name+' '+r.code).toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>sort==='cap'?(b.marketCap??-Infinity)-(a.marketCap??-Infinity):sort==='volume'?Math.max(...a.volumeRatios.map(v=>v??Infinity))-Math.max(...b.volumeRatios.map(v=>v??Infinity)):(a.rates[1]??Infinity)-(b.rates[1]??Infinity)),[scan.rows,filter,market,onlyFavorites,favorites,search,sort]);
  const progress=scan.total?Math.min(100,scan.stage==='quotes'?scan.checked/scan.total*70:70+(scan.detailTotal?scan.detailDone/scan.detailTotal*30:30)):0;
  function download(){const url=URL.createObjectURL(new Blob([reversalCSV(rows)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`balta-reversal-${scan.date}-${filter}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <section className={s.root} aria-label="급락 반등 후보">
    <div className={s.hero}><div><span className={s.eyebrow}>발타툴 · 조건 검색</span><h2>급락 반등 후보 <span>실험 전략</span></h2><p>거래량이 크게 늘지 않은 대형주의 연속 하락을 찾습니다.</p></div><button className={s.scanButton} onClick={()=>{setSelected('');void start();}} disabled={running}>{running?'후보 검색 중…':scan.date?'전체 재조회':'후보 검색 시작'}<span aria-hidden="true"> ↗</span></button></div>
    <div className={s.rules}><div><small>01 · 규모</small><strong>시가총액 ≥ 1조</strong></div><div><small>02 · 가격</small><strong>−5% 이하 음봉 × 2일</strong></div><div><small>03 · 거래량</small><strong>각 20일 평균 ≤ 150%</strong></div><div><small>04 · 하한가</small><strong>최근 20거래일 미접촉</strong></div></div>
    <div className={s.summary}>
      <button aria-pressed={filter==='match'} onClick={()=>setFilter('match')}><span>조건 충족 후보</span><strong>{scan.date?counts.match:'—'}<small>종목</small></strong><i>확인된 조회값 기준</i></button>
      <button aria-pressed={filter==='review'} onClick={()=>setFilter('review')}><span>확인 필요</span><strong>{scan.date?counts.review:'—'}<small>종목</small></strong><i>누락 · 기준가격 변동</i></button>
      <button aria-pressed={filter==='excluded'} onClick={()=>setFilter('excluded')}><span>상세 검토 후 제외</span><strong>{scan.date?counts.excluded:'—'}<small>종목</small></strong><i>조건별 제외 사유 제공</i></button>
      <div className={s.coverage}><span>시세 조회 진행</span><strong>{number(scan.checked)}<small> / {number(scan.total)}</small></strong><i>조회 실패·누락 {scan.issues.length}종목</i></div>
    </div>
    <div className={s.runInfo} aria-live="polite"><div><span className={s.phase}>{scan.date?(scan.phase==='intraday'?'장중 잠정':'장후 후보'):'조회 대기'}</span><strong>{scan.date||'최근 거래일'}</strong><span>{scan.saved?'이 브라우저에 저장된 결과 · ':''}{scan.date?`${time(scan.startedAt)} 검색 시작 · ${scan.stage==='done'?'조회 완료':scan.stage==='partial'?'일부 결과':running?'조회 중':'대기'}`:'검색을 시작하면 지원 종목 전체를 순차 조회합니다.'}</span></div>{running&&<button onClick={stop}>중지</button>}</div>
    {running&&<div className={s.progress}><progress value={progress} max="100" aria-label="후보 검색 진행률"/><span>{scan.stage==='detail'?`일봉 상세 검토 ${scan.detailDone} / ${scan.detailTotal}`:scan.total?`시세 확인 ${scan.checked} / ${scan.total} · 상세 검토 대상 ${scan.detailTotal}`:'종목 목록과 거래일 확인 중…'}</span></div>}
    <p className={s.note}>정규장 마감값 확정 여부는 미검증입니다. 장중·장후 모두 관찰 후보이며, 종목별 조회시점이 다릅니다. 시총은 최신 일봉 가격 × 현재 상장주수입니다.</p>
    {(error||storageError||favoriteError)&&<div className={s.warning} role="alert">{[error,storageError,favoriteError].filter(Boolean).join(' ')}</div>}
    {scan.stage==='partial'&&<p className={s.warning}>조회가 완료되지 않았거나 누락된 종목이 있습니다. 현재 숫자는 전체 시장의 최종 후보 수가 아닙니다.</p>}
    <div className={s.toolbar}><div className={s.filters} aria-label="후보 상태 필터">{[['match','후보'],['review','확인 필요'],['excluded','제외'],['all','상세 전체']].map(([v,label])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{label}</button>)}</div><label className={s.search}><span className={s.srOnly}>후보 검색</span><input type="search" aria-label="후보 검색" placeholder="종목명 · 코드 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="후보 시장" value={market} onChange={e=>setMarket(e.target.value)}><option value="all">전체 시장</option><option value="kospi">KOSPI</option><option value="kosdaq">KOSDAQ</option></select><select aria-label="후보 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="decline">당일 하락률순</option><option value="cap">시가총액순</option><option value="volume">거래량 비율순</option></select><label className={s.favoriteFilter}><input type="checkbox" checked={onlyFavorites} onChange={e=>setOnlyFavorites(e.target.checked)}/>관심만</label><button className={s.export} onClick={download} disabled={!rows.length}>CSV 저장 ↓</button></div>
    <div className={s.tableWrap}><table><thead><tr><th><span className={s.srOnly}>관심 표시</span>☆</th><th>종목 / 흐름</th><th>시가총액</th><th>전일 등락률</th><th>당일 등락률</th><th>거래량 / 20일 평균<small>전일 · 당일</small></th><th>20일 하한가</th><th>상태 / 분석</th></tr></thead><tbody>{rows.map(r=><Fragment key={r.code}><tr data-reversal-row={r.code}><td><button className={s.star} aria-label={`${r.name} 관심 표시`} aria-pressed={favorites.includes(r.code)} onClick={()=>toggle(r.code)}>{favorites.includes(r.code)?'★':'☆'}</button></td><td><a href={'/stock-flow?code='+r.code} target="_blank" rel="noopener noreferrer" className={s.stock}><strong>{r.name} ↗</strong><small>{r.code} · {r.market.toUpperCase()}</small></a><span className={s.spark}><Spark values={r.closes}/></span></td><td>{r.marketCap===null?'—':number(r.marketCap/1e12,2)+'조'}<small>{number(r.close)}원</small></td><td className={s.down}>{percent(r.rates[0])}</td><td className={s.down}>{percent(r.rates[1])}</td><td><span className={r.volumeRatios[0]!==null&&r.volumeRatios[0]>150?s.fail:s.value}>{number(r.volumeRatios[0],1)}{r.volumeRatios[0]!==null?'%':''}</span><span className={s.divider}> / </span><span className={r.volumeRatios[1]!==null&&r.volumeRatios[1]>150?s.fail:s.value}>{number(r.volumeRatios[1],1)}{r.volumeRatios[1]!==null?'%':''}</span></td><td><span className={s[r.checks.limit]}>{r.checks.limit==='pass'?'미접촉 · 산출':r.checks.limit==='fail'?'접촉 이력':'확인 필요'}</span></td><td><span className={s.badge} data-status={r.status}>{reversalStatus[r.status]}</span><button className={s.detailButton} onClick={()=>setSelected(selected===r.code?'':r.code)} aria-expanded={selected===r.code}>조건 상세 {selected===r.code?'−':'+'}</button></td></tr>{selected===r.code&&<tr><td colSpan={8} className={s.detailCell}><Detail row={r}/></td></tr>}</Fragment>)}</tbody></table>
      {!rows.length&&<div className={s.empty}><span aria-hidden="true">⌕</span><strong>{!scan.date?'네 가지 조건을 한 번에 확인하세요':running?'조회된 결과를 기다리는 중입니다':filter==='match'&&scan.stage==='done'&&!search&&!onlyFavorites&&market==='all'?'이번 조회에서 조건을 충족한 후보가 없습니다':'현재 필터에 표시할 종목이 없습니다'}</strong><p>{!scan.date?'후보 검색 시작을 누르면 지원 종목의 시세 확인 후 해당 종목의 일봉을 검토합니다.':scan.stage==='partial'?'미조회·실패 종목에 후보가 있을 수 있습니다. 전체 재조회해 주세요.':'확인 필요·제외 탭에서 판별 내역을 살펴볼 수 있습니다.'}</p></div>}
    </div><p className={s.footer}>표시 {rows.length}종목 · 표를 좌우로 밀어 전체 항목 확인 · 예비 시세에서 당일 −5% 이하 음봉인 종목만 상세 검토 · 관심 표시와 마지막 결과는 이 브라우저에 저장</p>
    {scan.issues.length>0&&<details className={s.explanation}><summary>조회 실패·누락 {scan.issues.length}종목</summary><p>{scan.issues.map(i=>`${i.name}(${i.code}) · ${i.stage==='quotes'?'시세':'일봉'}`).join(' / ')}</p><p>누락 종목은 조건 제외로 처리하지 않습니다. 전체 재조회로 다시 확인하세요.</p></details>}
    <details className={s.explanation}><summary>판별 기준과 매매 규칙</summary><div className={s.method}><div><h3>후보 계산 기준</h3><p>조회 범위: KIS 목록의 6자리 숫자코드 KOSPI·KOSDAQ 주권(ST). 우선주는 포함하고 영문 포함 코드·ETF·ETN·예탁증서는 제외합니다. 종목 목록은 최대 24시간 캐시됩니다.</p><ul><li>시가총액 1조원 이상. 최신 일봉 가격에 조회 시점 상장주수를 곱합니다.</li><li>두 거래일 모두 종가가 시가보다 낮고, 전일 종가 대비 수익률이 −5% 이하입니다. 정확히 −5%도 포함합니다.</li><li>각 신호일 거래량을 해당 일자를 제외한 직전 20거래일 평균으로 나눕니다. 각각 150% 이하여야 합니다.</li><li>당일 포함 20거래일의 저가와 산출 하한가를 비교합니다. KIS 하한가 마감 부호도 확인합니다. 권리락·재평가·기준가격 불일치·누락일은 통과시키지 않습니다.</li><li>거래일은 KIS 지수 일봉으로 확인합니다. 최근 22거래일 가격·거래량이 온전해야 합니다.</li></ul></div><div><h3>원안의 매매 규칙</h3><ul><li>두 번째 하락일 종가를 매수 기준으로 관찰합니다.</li><li>매수 다음 거래일이 음봉이면 그날 종가 청산입니다.</li><li>이후 양봉 두 개가 연속되면 두 번째 양봉 종가 청산입니다. 실제 손익은 별도 계산해야 합니다.</li></ul><p>현재 화면은 후보 검색입니다. 자동 주문·보유 추적·과거 성과 백테스트는 포함하지 않습니다. 종가 신호를 확인한 뒤 같은 종가에 체결할 수 있다고 가정하지 않습니다.</p><p>장중 누적 거래량은 하루 전체 거래량보다 작으므로 장 마감 후 다시 확인하세요. 정규장과 장후 거래의 일봉 집계 범위는 실데이터 검증이 필요합니다.</p><a href="https://regulation.krx.co.kr/contents/RGL/03/03010100/RGL03010100T5.jsp" target="_blank" rel="noopener noreferrer">KRX 하한가 산출 기준 ↗</a></div></div></details>
  </section>;
}
function Detail({row:r}:{row:ReversalResult}) {return <div className={s.detail}><div className={s.checks}>{Object.entries(reversalLabels).map(([k,label])=><div key={k}><span>{label}</span><b className={s[r.checks[k as keyof typeof r.checks]]}>{checkNames[r.checks[k as keyof typeof r.checks]]}</b></div>)}</div><p>{r.reasons.length?r.reasons.join(' / '):'조회된 데이터에서 네 조건을 충족했습니다. 정규장 마감·체결 가능 여부를 별도로 확인하세요.'}</p><p>전일 거래량 {number(r.volumes[0])}주 / 직전 평균 {number(r.averages[0],1)}주 · 당일 {number(r.volumes[1])}주 / 직전 평균 {number(r.averages[1],1)}주</p><div className={s.links}><a href={'/stock-flow?code='+r.code} target="_blank" rel="noopener noreferrer">수급 차트 · 공시 ↗</a><a href={'/cash-flow?code='+r.code} target="_blank" rel="noopener noreferrer">기업 현금흐름 ↗</a><span>기준일 {r.date} · 조회 {time(r.asOf)} KST</span></div></div>;}
