-- Run once in Supabase SQL Editor before deploying the updated collector.
-- Additive: existing logs and kis_tokens are retained. Repeatable migration.
begin;
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  createdat text not null, time text not null,
  created_at timestamptz not null default now(),
  up integer, down integer, flat integer, diff integer, accel integer,
  upratio double precision, downratio double precision,
  kospi double precision, kosdaq double precision,
  foreignflow double precision, instflow double precision, indivflow double precision,
  flowpower double precision, flowtrend double precision, flowmomentum double precision,
  alert text, markettone text, marketscore integer, marketstate text, signals jsonb
);
alter table public.logs add column if not exists market_data jsonb;
create index if not exists logs_history_date_time_idx on public.logs (createdat, time, id desc);
create table if not exists public.kis_tokens (
 id text primary key, access_token text not null, expires_at timestamptz not null, updated_at timestamptz not null default now()
);
create table if not exists public.market_daily (
 trade_date date primary key,
 snapshot jsonb not null,
 updated_at timestamptz not null default now(),
 constraint market_daily_snapshot_date check (snapshot->>'createdat'=trade_date::text)
);
comment on table public.market_daily is 'Latest regular-session snapshot per KST date; flows and turnover are daily cumulative, never summed intraday. 15:30 snapshot is closing observation, not exchange-certified data.';
create or replace function public.capture_market_daily() returns trigger
language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 if new.createdat::text !~ '^\d{4}-\d{2}-\d{2}$'
   or new.time::text !~ '^(09|1[0-4]):[0-5][0-9]$|^15:([0-2][0-9]|30)$'
   or coalesce(new.up,0)+coalesce(new.down,0)+coalesce(new.flat,0)<=0 then return new; end if;
 insert into public.market_daily(trade_date,snapshot,updated_at)
 values (new.createdat::date,to_jsonb(new)-'signals',now())
 on conflict(trade_date) do update set snapshot=excluded.snapshot,updated_at=now()
 where (excluded.snapshot->>'time')>(market_daily.snapshot->>'time')
    or ((excluded.snapshot->>'time')=(market_daily.snapshot->>'time')
      and (excluded.snapshot->>'id')::bigint >= (market_daily.snapshot->>'id')::bigint);
 return new;
end $$;
drop trigger if exists logs_market_daily_capture on public.logs;
create trigger logs_market_daily_capture after insert or update on public.logs
for each row execute function public.capture_market_daily();
-- Rebuild older summaries from actual saved snapshots; never fabricate absent fields.
insert into public.market_daily(trade_date,snapshot)
select distinct on (createdat) createdat::date,to_jsonb(l)-'signals'
from public.logs l
where createdat::text ~ '^\d{4}-\d{2}-\d{2}$'
 and time::text ~ '^(09|1[0-4]):[0-5][0-9]$|^15:([0-2][0-9]|30)$'
 and coalesce(up,0)+coalesce(down,0)+coalesce(flat,0)>0
order by createdat,time desc,id desc
on conflict(trade_date) do update set snapshot=excluded.snapshot,updated_at=now()
where (excluded.snapshot->>'time') >= (market_daily.snapshot->>'time');
alter table public.logs enable row level security;
revoke all on public.logs from anon,authenticated;
grant all on public.logs to service_role;
alter table public.market_daily enable row level security;
revoke all on public.market_daily from anon,authenticated;
grant all on public.market_daily to service_role;
-- Tokens must remain server-only; the application uses its existing service role.
alter table public.kis_tokens enable row level security;
revoke all on public.kis_tokens from anon,authenticated;
grant all on public.kis_tokens to service_role;
revoke all on function public.capture_market_daily() from public;
notify pgrst, 'reload schema';
commit;
